### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by panicape** [romus/sha#2]
Good morning / Afternoon / evening
I would like to know if this implementation is correct or not. I check comments and it says that it generates an invalid hash, could be nice more detailed comments.
if this implementation is wrong, do you know when can i find a good implementation of sha-3 algorithm?

**Comment by romus** [comment]
Hello!

The current implementation is relevant until the adoption of [FIPS 202](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf).
You can look at [js-sha3](https://github.com/emn178/js-sha3), where these changes were included.

**Comment by panicape** [comment]
ok, thanks

**Comment by romus** [comment]
Yep. This is javascript implementation.
I provide the FIPS 202 changes when I will have time...

**Comment by aradej006** [comment]
I analysed your code and in your code is one thing what you should do to provide the FIPS 202. In padding method you are adding to message "01" if you add "06" you will get SHA3-224, SHA3-256, SHA3-384, SHA3-512 and if you add "1f" you will get SHAKE128 or SHAKE256. 

In the FIPS 202, byte "01" is named as d, but in your code it is output length in bytes.

**Comment by romus** [comment]
Thx @aradej006 !

Implementation here - 91c2be1d0a0d62449f93494ab3f6204d66460877
