### ISSUE TITLE
Hash wrong for certain input

### ISSUE THREAD

**Issue by ligi** [romus/sha#4]
keccak-256

for 

`a1b31be4d58a7ddd24b135db0da56a90fb5382077ae26b250e1dc9cd6232ce2270f4c995428bc76aa78e522316e95d7834d725efc9ca754d043233af6ca90113`

is calculated as:
`df49991eec8137d9f7f9ad5edd84bd0369ecc73823f6f4a55b08aee9bdeeb7dc`

but should be

`3beffbe4b37afd6b805637b37c0bede67e79f6f76174e0fdd2188ae696604d4e`

interestingly other input I tested is OK - not yet sure why it fails for this one..

**Comment by ligi** [comment]
I am not on my PC currently. But seeing the URL to check you linked indicates you do not test the input as a hash. Sorry I did not specify explicitly. This online converter supports hash input https://www.decrane.io/keccak

On 15 October 2017 11:35:54 PM GMT+02:00, Roman <notifications@github.com> wrote:
>Hello!
>
>Why should the result be
>```3beffbe4b37afd6b805637b37c0bede67e79f6f76174e0fdd2188ae696604d4e```?
>
>It mast be
>```2ffc688a3249e25a411cb5ac43f5efbbceb077d1f9e6a935aa9b22cfa6894357```
>(for keccak-256).
>
>Here is an example:
>```java
>import static com.theromus.sha.Parameters.KECCAK_256;
>import static com.theromus.utils.HexUtils.getHex;
>
>import com.theromus.sha.Keccak;
>
>
>public class CheckK256 {
>
>    public static void main(String[] args) {
>String testString =
>"a1b31be4d58a7ddd24b135db0da56a90fb5382077ae26b250e1dc9cd6232ce2270f4c995428bc76aa78e522316e95d7834d725efc9ca754d043233af6ca90113";
>        String testString2 = getHex(testString.getBytes());
>
>        Keccak keccak = new Keccak();
>
>System.out.println("Without getHash().getBytes() = " +
>keccak.getHash(testString, KECCAK_256));
> System.out.println("Ok = " + keccak.getHash(testString2, KECCAK_256));
>    }
>
>}
>```
>
>Out:
>```
>Without getHash().getBytes() =
>df49991eec8137d9f7f9ad5edd84bd0369ecc73823f6f4a55b08aee9bdeeb7dc
>Ok = 2ffc688a3249e25a411cb5ac43f5efbbceb077d1f9e6a935aa9b22cfa6894357
>```
>
>You can check the result on
>[k256](https://emn178.github.io/online-tools/keccak_256.html)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/romus/sha/issues/4#issuecomment-336743396

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ligi** [comment]
as hash->as hex

On 15 October 2017 11:35:54 PM GMT+02:00, Roman <notifications@github.com> wrote:
>Hello!
>
>Why should the result be
>```3beffbe4b37afd6b805637b37c0bede67e79f6f76174e0fdd2188ae696604d4e```?
>
>It mast be
>```2ffc688a3249e25a411cb5ac43f5efbbceb077d1f9e6a935aa9b22cfa6894357```
>(for keccak-256).
>
>Here is an example:
>```java
>import static com.theromus.sha.Parameters.KECCAK_256;
>import static com.theromus.utils.HexUtils.getHex;
>
>import com.theromus.sha.Keccak;
>
>
>public class CheckK256 {
>
>    public static void main(String[] args) {
>String testString =
>"a1b31be4d58a7ddd24b135db0da56a90fb5382077ae26b250e1dc9cd6232ce2270f4c995428bc76aa78e522316e95d7834d725efc9ca754d043233af6ca90113";
>        String testString2 = getHex(testString.getBytes());
>
>        Keccak keccak = new Keccak();
>
>System.out.println("Without getHash().getBytes() = " +
>keccak.getHash(testString, KECCAK_256));
> System.out.println("Ok = " + keccak.getHash(testString2, KECCAK_256));
>    }
>
>}
>```
>
>Out:
>```
>Without getHash().getBytes() =
>df49991eec8137d9f7f9ad5edd84bd0369ecc73823f6f4a55b08aee9bdeeb7dc
>Ok = 2ffc688a3249e25a411cb5ac43f5efbbceb077d1f9e6a935aa9b22cfa6894357
>```
>
>You can check the result on
>[k256](https://emn178.github.io/online-tools/keccak_256.html)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/romus/sha/issues/4#issuecomment-336743396

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by romus** [comment]
Thanks!
I'll take a look at this later.

**Comment by romus** [comment]
Are you sure the line (```a1b31be4d58a7ddd24b135db0da56a90fb5382077ae26b250e1dc9cd6232ce2270f4c995428bc76aa78e522316e95d7834d725efc9ca754d043233af6ca90113 ```) is in base16 encoding?

**Comment by ligi** [comment]
sorry - completely missed the question - can swear I got no notification.

Yes I am sure string is base16.
What you can do is to compare with the hash from bouncycastle - I am now using this implementation.

**Comment by romus** [comment]
I'll try to see when I have time.

**Comment by ligi** [comment]
Did you find some time?

**Comment by romus** [comment]
I hope to get to the issue in the near future.
ср, 13 дек. 2017 г. в 15:44, ligi <notifications@github.com>:

**Comment by ligi** [comment]
gentle push ;-)

**Comment by ligi** [comment]
Hey @romus - great to see you found some time working on it - also the comment of @svegaxmr here (https://github.com/walleth/keccak/issues/4) indicates that already solves the problem - just interested why you did not yet merge it to master. Do you see any problems with this change?

**Comment by romus** [comment]
Hello, @ligi 

Sorry for delay. Merged. Please check your case.

**Comment by ligi** [comment]
Hey thanks!
The test-case above looks good now - unfortunately when playing around with it I found another problem.
It does not return the wrong result there - but does not terminate.

See the test here: 
https://github.com/ligi/compare_romus_bouncycastle_keccak

If you uncomment the test-vector:

`"The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.The quick brown fox jumps over the lazy dog.".toByteArray(),
`

you should see the problem

**Comment by ligi** [comment]
The problem is in the Absorbing phase:

```
 // Absorbing phase
        while (inputOffset < uMessage.length) {
            blockSize = min(uMessage.length - inputOffset, rateInBytes);
            for (int i = 0; i < blockSize; i++) {
                uState[i] = uState[i] ^ uMessage[i + inputOffset];
            }

            if (blockSize == rateInBytes) {
                doKeccakf(uState);
                blockSize = 0;
            }

            inputOffset = inputOffset + blockSize;
        }
```

so when the input is bigger than the blockSize we get in the loop as blockSize is always 0

**Comment by romus** [comment]
Thanks for feedback! I'll fix it now.

**Comment by romus** [comment]
Fixed potential bug. Plz check it.

**Comment by ligi** [comment]
Great! FYI - when making the Kotlin version I did a optimisation to convertFromLittleEndianTo64 - maybe you want to backport:

```kotlin
internal fun convertFromLittleEndianTo64(data: IntArray) =
        BigInteger(data.map { Integer.toString(it, 16) }
                .map { if (it.length == 2) it else "0$it" }
                .reversed()
                .joinToString("")
                , 16)
```
so no shifting is needed and only one parsing step - should be much faster - did not measure though

**Comment by romus** [comment]
OK, I'll take a look.

**Comment by ligi** [comment]
just had a look through 98117f5be45ebab9ee7a71f2f4f4f0f4a4fd5e07 - do you have any input/test-case where the code before would produce a wrong result?

**Comment by romus** [comment]
Yep, 
you can download [NIST test vectors](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha-3bittestvectors.zip) (SHA3_256ShortMsg.rsp):
```
Len = 1088
Msg = 355f6ecd76db7f49373abad520179a0e2b1588caa7d1fea98315ededc94f5c8b6941528138f9f76b3804f6511adf25c401ae68298930d35408f30e5914c4fe9e456aa1353b943a69e30faf97f73c2f40c4c2175b308017f0fbc691e245c4410d514223908892916cc1c3ac4fbf18feaafbb85e09a4a713a4e5f53c3166366ffd1532a03b26dd449c
MD = 8cd9578badf02409cc7d336600eb796340a3132236cb3af7bea7686ddddb7fa2
```

And check this:
```java
Keccak keccak = new Keccak();

// convert hex MSG to byte-array
String msg = "355f6ecd76db7f49373abad520179a0e2b1588caa7d1fea98315ededc94f5c8b6941528138f9f76b3804f6511adf25c401ae68298930d35408f30e5914c4fe9e456aa1353b943a69e30faf97f73c2f40c4c2175b308017f0fbc691e245c4410d514223908892916cc1c3ac4fbf18feaafbb85e09a4a713a4e5f53c3166366ffd1532a03b26dd449c";
byte[] tba = convertHexStringToByteArray(msg);
int len = 1088;
byte[] bMsg = new byte[len / 8];
System.arraycopy(tba, 0, bMsg, 0, bMsg.length);

String md = "8cd9578badf02409cc7d336600eb796340a3132236cb3af7bea7686ddddb7fa2";
String result = HexUtils.convertBytesToString(keccak.getHash(bMsg, SHA3_256));

System.out.println(result + "; md = result: " +  md.equals(result));
// ad3d9c1ed1dbb575c8182a92539a912243d0a86807ad8d54e90656c7919db73d; md = result: false
```

I'll try to write some tests for hashing later.

**Comment by ligi** [comment]
Thanks!
having a bit of trouble understanding these vectors currently - wouldnt:

```
Len = 0
Msg = 00
MD = a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a

Len = 1
Msg = 00
MD = 1b2e61923578e35f3b4629e04a0ff3b73daa571ae01130d9c16ef7da7a4cfdc2
```

generate the same hash with the code above as both lead to an array with size 0?

**Comment by ligi** [comment]
ah this only seems applicable if you have a function that takes bits as input - as we take only whole bytes as input I just dropped all with len%8 != 0 now - maybe you can also use this extract:
https://github.com/walleth/sha3/blob/master/sha3/src/test/kotlin/org/walleth/sha3/TestVectorsNist.kt
